code --install-extension dzhavat.bracket-pair-toggler
code --install-extension EliverLara.andromeda
code --install-extension formulahendry.auto-rename-tag
code --install-extension GitHub.copilot
code --install-extension IBM.output-colorizer
code --install-extension ms-azuretools.vscode-docker
code --install-extension MS-CEINTL.vscode-language-pack-fr
code --install-extension ms-vscode-remote.remote-containers
code --install-extension solnurkarim.html-to-css-autocompletion